# Example:
# Add 'label2' to any file changes within 'example2' folder
# label2: example2/*

Code: 
  - code/**/*
  
Icon:
  - icons/**/*
  
Sound:
  - sounds/**/*
  
Interface:
  - html/**/*
  - interface/**/*
  - scripts/**/*
  
Data:
  - data/**/*
  - settings/**/*
  - config/**/*
  
Github:
  - .git/**/*
  - .github/**/*
